name: Bleeding Edge GCC Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 6'

env:
  GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: diazaji/debian:toolchain
    steps:
    - uses: actions/checkout@v4
    - name: Force safe directory
      run: git config --global --add safe.directory '*'
    - name: Download Resources
      run: ./resources.sh master
    - name: Build & Release
      run: ./build.sh master
