name: GCC+LLD Build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * 0,2,4,6'

env:
      GITHUB_EMAIL: ${{ secrets.EMAIL }}
      GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      GITHUB_USER: ${{ secrets.USERNAME }}
      BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT }}

jobs:
  build-tc:
    runs-on: buildjet-64vcpu-ubuntu-2204
    container:
      image: diazaji/debian:gcc
    steps:
    - uses: actions/checkout@v3
    - name: Download Resources
      run: ./download-resources.sh
    - name: Build & Release
      run: ./build-gcc.sh
