name: Bleeding Edge GCC Build

on:
  schedule:
    - cron: '0 23 * * 6'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
  BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: diazaji/debian:gcc
    steps:
    - uses: actions/checkout@v3
    - name: Force safe directory
      run: git config --global --add safe.directory '*'
    - name: Download Resources
      run: ./resources.sh master
    - name: Build & Release
      run: ./build.sh master
